[project]
name = "multi-agent-training"
version = "0.1.0"
description = "Multi-agent training project"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[target.linux-64.dependencies]
python = "3.12.*"
fastapi = "*"
uvicorn = "*"
pika = "*"
redis-py = "*"
python-dotenv = "*"
pydantic = "*"
websockets = "*"
aiohttp = "*"

[tasks]
start = "python -m uvicorn main:app --reload"
